In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [16]:
data_csv=np.loadtxt("./data.csv",delimiter=",",dtype="int")

In [17]:
print(data_csv)

[[ 1  2  3]
 [ 2 34  5]]


In [18]:
print(data_csv[:,2:])

[[3]
 [5]]


In [19]:
data_csv[1,1]=1

In [20]:
print(data_csv)

[[1 2 3]
 [2 1 5]]


In [22]:
data_csv[data_csv<2]=0

In [23]:
print(data_csv)

[[0 2 3]
 [2 0 5]]
